export const glyphPages = [
  {
    id: 'p1',
    promptTop: 'Ancient voices rise from\nthe papyrus scrolls...',
    promptBottom:
      'At sunrise, the falcon\nwatches the dunes. Name\nthe sky god',
    answers: ['horus', 'horus.'],
    successText: 'Truth flows through your words',
    failText: 'The desert grows silent; that answer is lost to time',
  },
  {
    id: 'p2',
    promptTop: 'Ancient voices rise from\nthe papyrus scrolls...',
    promptBottom:
      'In judgment, a heart is weighed\nagainst a single sacred feather.\nWhose feather?',
    answers: ['maat', "ma'at", 'maat', 'maat.'],
    successText: 'Balance is restored',
    failText: 'Not yet — the scale waits',
  },
  {
    id: 'p3',
    promptTop: 'Ancient voices rise from\nthe papyrus scrolls...',
    promptBottom:
      'The sun god battles a serpent\neach night. Name the serpent.',
    answers: ['apep', 'apophis', 'apeph'],
    successText: 'The serpent recoils into shadow',
    failText: 'The night is long; try again',
  },
  {
    id: 'p4',
    promptTop: 'Ancient voices rise from\nthe papyrus scrolls...',
    promptBottom: 'Lioness of scorching wrath who\ncan also heal—name her.',
    answers: ['sekhmet', 'sekhemet', 'sekmet'],
    successText: 'Her fierce grace recognizes you',
    failText: 'Her flames wait — answer again',
  },
  {
    id: 'p5',
    promptTop: 'Ancient voices rise from\nthe papyrus scrolls...',
    promptBottom: 'Scarab that rolls the sun\nacross the horizon—who is it?',
    answers: ['khepri', 'khepra', 'kheper'],
    successText: 'The scarab nods as the sun is pushed along',
    failText: 'The sun’s path remains unfulfilled',
  },
  {
    id: 'p6',
    promptTop: 'Ancient voices rise from\nthe papyrus scrolls...',
    promptBottom: 'Ibis-headed keeper of writing\nand measure—name him.',
    answers: ['thoth', 'thot', 'dhwty', 'djehuty'],
    successText: 'Words and measures fall into order',
    failText: 'The ink is not ready — try again',
  },
  {
    id: 'p7',
    promptTop: 'Ancient voices rise from\nthe papyrus scrolls...',
    promptBottom: 'The united royal headdress\nof North and South—its name?',
    answers: ['double crown', 'pschent', 'pschent.'],
    successText: 'The crown is raised in recognition',
    failText: 'The headdress remains hidden — answer again',
  },
  {
    id: 'p8',
    promptTop: 'Ancient voices rise from\nthe papyrus scrolls...',
    promptBottom:
      'Great tomb that rises from\ntriangles toward the sky—name it.',
    answers: ['pyramid', 'pyramids', 'the pyramid'],
    successText: 'You see the triangular shadow on the sand',
    failText: 'The sands obscure the shape — try again',
  },
  {
    id: 'p9',
    promptTop: 'Ancient voices rise from\nthe papyrus scrolls...',
    promptBottom: 'Jackal-faced guardian of\nembalming—who guides the dead?',
    answers: ['anubis', 'anpu', 'inpw'],
    successText: 'The jackal leads the way',
    failText: 'The path is not clear — answer once more',
  },
  {
    id: 'p10',
    promptTop: 'Ancient voices rise from\nthe papyrus scrolls...',
    promptBottom: 'The green-skinned lord\nrestored by his sister—name him.',
    answers: ['osiris'],
    successText: 'Life stirs in the green fields',
    failText: 'The tomb holds its secret still',
  },
  {
    id: 'p11',
    promptTop: 'Ancient voices rise from\nthe papyrus scrolls...',
    promptBottom: 'His red-hot rival, lord\nof desert and storms—name him.',
    answers: ['set', 'seth'],
    successText: 'The storm answers your name',
    failText: 'The desert wind hushes your words',
  },
  {
    id: 'p12',
    promptTop: 'Ancient voices rise from\nthe papyrus scrolls...',
    promptBottom: 'Star whose rising foretold the\nNile flood—its name?',
    answers: ['sirius', 'sothis'],
    successText: 'The star blazes in the heavens',
    failText: 'The waters wait for a truer answer',
  },
  {
    id: 'p13',
    promptTop: 'Ancient voices rise from\nthe papyrus scrolls...',
    promptBottom: 'Protective eye amulet worn on\nthe chest—what’s it called?',
    answers: ['wedjat', 'wadjet', 'eye of horus', 'udjat', 'wedjat.'],
    successText: 'The amulet warms with approval',
    failText: 'The amulet remains cold — try again',
  },
  {
    id: 'p14',
    promptTop: 'Ancient voices rise from\nthe papyrus scrolls...',
    promptBottom:
      'Cow-horn crown with moon disk,\ngoddess of joy and music—who?',
    answers: ['hathor', 'hwt-hr', 'hat-hor'],
    successText: 'Music fills the air at your word',
    failText: 'Silence answers — attempt again',
  },
  {
    id: 'p15',
    promptTop: 'Ancient voices rise from\nthe papyrus scrolls...',
    promptBottom: 'Single word for cosmic order and\ntruth—name it.',
    answers: ['maat', "ma'at", 'maat.'],
    successText: 'Order settles like water',
    failText: 'Chaos lingers — try again',
  },
  {
    id: 'p16',
    promptTop: 'Ancient voices rise from\nthe papyrus scrolls...',
    promptBottom: 'Blue desert flower sacred\nto rebirth—name it.',
    answers: ['lotus', 'blue lotus', 'water lily'],
    successText: 'Petals unfold with your answer',
    failText: 'The bloom remains closed — answer again',
  },
];
